### ISSUE TITLE
Error creating index - class Array not found

### ISSUE THREAD

**Issue by LukeMauldin** [m2mdas/phpcomplete-extended-laravel#2]
I am creating an index on a rather large Laravel project.  I am getting the error below:

The lines of code in question are:
  // Set the EAV facade.
        $this->app['eav'] = $this->app->share(
            function ($app) {
                $manager_class = (string)$app['config']['eav::attribute_manager'];
                //Error occurs on next line, line 78
                $eav = new $manager_class($app['config']['eav::config.cache'], $app['config']['eav::config.cache_entry']);
                $eav->setEavModels($app['config']['eav::config.eav_models']);
                $eav->setDataTypes($app['config']['eav::config.data_types']);
                $eav->setRelatableModels($app['config']['eav::relatable_models']);

```
            return $eav;
        }
    );
```

Call Stack:
    0.0017     567280   1. {main}() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:0
    0.0096    1678192   2. IndexGenerator->addPlugin() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:54
    0.0101    1779648   3. include('/Users/lmauldin/.vim/bundle/phpcomplete-extended-laravel/bin/laravel.php') /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:247

PHP Fatal error:  Class 'Array' not found in /Users/lmauldin/dev/pe/apps/ngt/vendor/evolution/eav/src/Evolution/Eav/EavServiceProvider.php on line 78
PHP Stack trace:
PHP   1. {main}() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:0
PHP   2. IndexGenerator->generateIndex() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:57
PHP   3. IndexGenerator->execHook() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:527
PHP   4. call_user_func_array() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:277
PHP   5. laravel->postCreateIndex() /Users/lmauldin/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php:277
PHP   6. laravel->processIndex() /Users/lmauldin/.vim/bundle/phpcomplete-extended-laravel/bin/laravel.php:209
PHP   7. laravel->processIoc() /Users/lmauldin/.vim/bundle/phpcomplete-extended-laravel/bin/laravel.php:266
PHP   8. Illuminate\Foundation\Application->make() /Users/lmauldin/.vim/bundle/phpcomplete-extended-laravel/bin/laravel.php:287
PHP   9. Illuminate\Container\Container->make() /Users/lmauldin/dev/pe/apps/ngt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:423
PHP  10. Illuminate\Container\Container->build() /Users/lmauldin/dev/pe/apps/ngt/workbench/evolution/tasking/vendor/illuminate/container/Illuminate/Container/Container.php:416
PHP  11. Illuminate\Container\Container->Illuminate\Container{closure}() /Users/lmauldin/dev/pe/apps/ngt/workbench/evolution/tasking/vendor/illuminate/container/Illuminate/Container/Container.php:473
PHP  12. Evolution\Eav\EavServiceProvider->Evolution\Eav{closure}() /Users/lmauldin/dev/pe/apps/ngt/workbench/evolution/tasking/vendor/illuminate/container/Illuminate/Container/Container.php:207
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Array' not found","file":"\/Users\/lmauldin\/dev\/pe\/apps\/ngt\/vendor\/evolution\/eav\/src\/Evolution\/Eav\/EavServiceProvider.php","line":78}}{"error":{"type":"Symfony\C
omponent\Debug\Exception\FatalErrorException","message":"Class 'Array' not found","file":"\/Users\/lmauldin\/dev\/pe\/apps\/ngt\/vendor\/evolution\/eav\/src\/Evolution\/Eav\/EavServiceProvider.php","line":78}}

**Comment by m2mdas** [comment]
Sorry for late reply as I did not sit in front of my PC yesterday. 

From the first glance it seems that `$manager_class` is interpreted as `Array` after `string` casting. Can you look into that? I can wrap the ioc creation code in `try/catch` but it will not be full proof as PHP does not catch exceptions of parent class, instead it gives a fatal error. It was a big headache while developing this plugin.

**Comment by LukeMauldin** [comment]
I added a dd($manager_class) after this line:
$manager_class = (string)$app['config']['eav::attribute_manager'];

It seems that the attribute_manager config value didn't exist so the config was returning an empty array, which was causing the problems.  Would it be possible for the indexer to just log this exception and continue?

**Comment by m2mdas** [comment]
Just  tried to reset Laravel's  error handling mechanism(you can also try it by commenting [this](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/start.php#L150) line). It seems that PHP throws fatal error if Laravel can not create IOC service class. After that the indexer script can not proceed further. I am sorry to say that I can not implement the feature you requested because of this limitation.
