### ISSUE TITLE
Breaks with most recent laravel

### ISSUE THREAD

**Issue by jansenm** [m2mdas/phpcomplete-extended-laravel#4]
The Service Provider class got a new method so the wrappers in bin/ have to be reviewed. (The new function is when())

My last issue. I swear :)

**Comment by m2mdas** [comment]
Opps, deleted last comment.

Hey, no need to swear. Feel free to report as many issues you find. Thanks for your contribution. I have pushed the fix.

**Comment by jansenm** [comment]
Fixed it for me. Thx.
